"""
Django settings for simplechat project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import mimetypes

# Python's mimetypes module guesses ".webm" as "video/webm" on most systems,
# even though MediaRecorder produces audio-only webm blobs. Browsers refuse
# to play an <audio> element whose response Content-Type says "video/*", so
# without this override, uploaded voice messages save fine but silently
# fail to play back. Registering the correct types up front fixes that for
# every request served by Django (including the dev-server /media/ route).
mimetypes.add_type("audio/webm", ".webm")
mimetypes.add_type("audio/ogg", ".ogg")
mimetypes.add_type("audio/mp4", ".m4a")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(sgqzsry#sd*(w6--t_%x6qflfoz#xzov16tobmqjn^2gu_5=l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # ngrok's free tier gives you a new random subdomain each time you
    # start a tunnel, so this wildcards both of their domains rather
    # than hardcoding one URL that would stop working on your next run.
    '.ngrok-free.app',
    '.ngrok-free.dev',
    '.ngrok.io',
    '.ngrok.app',
]

# Django rejects cross-origin POSTs (login, signup, sending messages...)
# unless the origin is explicitly trusted. ngrok serves your app over
# https while Django itself still only knows about plain http, so this
# is required for forms/fetch POSTs to work through the tunnel at all.
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
    'https://*.ngrok.app',
]

# ngrok terminates TLS and forwards plain http to your local server, so
# without this Django would otherwise think every request is insecure
# even though the person is actually on https via the tunnel.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'chat.middlewares.IP.BlockBannedIPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'chat.middlewares.session.EnforceActiveSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chat.middlewares.middleware.UpdatePresenceMiddleware',
]

ROOT_URLCONF = 'simplechat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simplechat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Voice messages: cap upload size to keep things sane (5 MB, generous for
# a couple of minutes of compressed voice audio).
MAX_VOICE_MESSAGE_BYTES = 5 * 1024 * 1024

# Video messages: generous but still bounded (25 MB, roughly a
# 30-60 second clip at typical phone-camera compression).
MAX_VIDEO_MESSAGE_BYTES = 25 * 1024 * 1024

# Photos: phone camera photos are usually 2-8 MB.
MAX_PHOTO_MESSAGE_BYTES = 10 * 1024 * 1024

# Documents (PDFs, Office files, zips, etc).
MAX_DOCUMENT_MESSAGE_BYTES = 20 * 1024 * 1024

# Custom stickers people create from their own images - small on purpose,
# these are meant to be tiny icon-like images, not full photos.
MAX_STICKER_IMAGE_BYTES = 2 * 1024 * 1024

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'room'
LOGOUT_REDIRECT_URL = 'login'

# Lets AuthenticationForm.confirm_login_allowed() give a specific
# "pending approval" / "rejected" message for inactive accounts, instead
# of Django's generic "invalid credentials" message (see
# chat/backends.py and PendingAwareAuthenticationForm in chat/forms.py).
AUTHENTICATION_BACKENDS = [
    'chat.backends.AllowInactiveAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]