# Generated by Django 6.0.7 on 2026-07-15 06:35

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_sticker_message_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.document_message_path),
        ),
        migrations.AddField(
            model_name='message',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.photo_message_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('photo', 'Photo'), ('document', 'Document'), ('sticker', 'Sticker')], default='text', max_length=10),
        ),
    ]
