# Generated by Django 6.0.7 on 2026-07-17 09:26

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_deleted_alter_message_message_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to=chat.models.custom_sticker_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='custom_sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.customsticker'),
        ),
    ]
