# Generated by Django 6.0.7 on 2026-07-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_customsticker_message_custom_sticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='ISO code')),
                ('name', models.CharField(max_length=100)),
                ('dial_code', models.CharField(help_text="Without the leading '+'.", max_length=4, verbose_name='Dial code')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='country_iso2',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='dial_code',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', to='chat.country'),
        ),
    ]
