# Generated by Django 6.0.7 on 2026-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_country_remove_phonenumber_country_iso2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
